In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
lambda0 = 1
x0 = [1/5 ,-1/5 ,4/5]
x0 = np.array(x0).reshape(3,1)
A = np.array([4,2,1,2,3,0,1,0,1])
A = A.reshape(3,3)

In [3]:
A

array([[4, 2, 1],
       [2, 3, 0],
       [1, 0, 1]])

In [4]:
x0.shape

(3, 1)

In [5]:
eigvalues,eigvectors= np.linalg.eig(A)

In [6]:
eigvalues

array([5.69639278, 1.82180592, 0.4818013 ])

In [7]:
eigvectors

array([[-0.7916823 , -0.43184431, -0.43214537],
       [-0.58721586,  0.73306142,  0.34321785],
       [-0.16857242, -0.52548211,  0.83393758]])

In [8]:
def F(x,Lambda):
    x = x.reshape(3,1)
    F = ( A - Lambda*np.eye(3) )@x
    #F = np.vstack(F, x.T@x -1 )
    F = np.concatenate( (F, x.T@x -1 ) )
    return F

In [9]:
def grad_F(x,Lambda):
    x = x.reshape(3)
    grad = [  4 - Lambda, 2, 1,-x[0] ,
              2, 3 - Lambda,0,-x[1] ,
              1, 0, 1 - Lambda, -x[2] ,
              2*x[0], 2*x[1], 2*x[2],0 ]
    grad = np.array(grad,dtype = float)
    grad = grad.reshape(4,4)
    return grad

In [10]:
def grad_F_inv(x,Lambda):
    grad = grad_F(x,Lambda)
    grad_inv = np.linalg.inv(grad)
    return grad_inv 

# 3a  
# y is the combination of x and lambda

In [11]:
iter_max = 100
y_list = []
y_now =[]
y_next =np.array( [1/5 ,-1/5 ,4/5,1]).reshape(-1,1)
# y is the combination of x and lambda

Lambda = lambda0
x_now = x0
x_next = []

steps = 0

while np.abs( Lambda - eigvalues[1]) > 1e-3 :
    
    y_now = y_next
    y_next = y_now - grad_F_inv(x_now,Lambda)@F(x_now,Lambda)
    x_now = y_next[0:3 , :]
    Lambda = y_next[3]
    
    y_list.append(y_next)
    steps = steps+1
    
print("last y: \n",y_list[-1])
print("iteration steps: ", steps)

last y: 
 [[ 0.8652295 ]
 [-1.46862935]
 [ 1.05211505]
 [ 1.82128088]]
iteration steps:  8


<ipython-input-9-b2a47f2ac671>:7: DeprecationWarning: setting an array element with a sequence. This was supported in some cases where the elements are arrays with a single element. For example `np.array([1, np.array([2])], dtype=int)`. In the future this will raise the same ValueError as `np.array([1, [2]], dtype=int)`.
  grad = np.array(grad,dtype = float)


# 3b

In [12]:
def h(y):
    x = y[0:3]
    Lambda = y[3]
    val = 1/2* ( np.linalg.norm(F(x,Lambda)) **2)
    
    return val

In [13]:
def grad_h(x,Lambda):
    
    grad = grad_F(x,Lambda).T @ F(x,Lambda)
    
    return grad

In [15]:

y_list = []
y_now =[]
y_next =np.array( [1/5 ,-1/5 ,4/5,1]).reshape(-1,1)
# y is the combination of x and lambda

Lambda = lambda0
x_now = x0
x_next = []

steps = 0

eta = 0.1
tau = 0.9
alpha = 100

while np.abs( Lambda - eigvalues[1]) > 1e-3 :
    
    y_now = y_next

    alpha_now = alpha # initial step size
    
    while True:
        a = h(y_now - alpha_now*grad_h(x_now,Lambda) )
        b = (h(y_now)- eta*alpha_now*(np.linalg.norm(grad_h(x_now,Lambda))**2 ))
        if(a<b):
            break
        alpha_now = alpha_now*tau
    
    y_next = y_now - alpha_now*grad_h(x_now,Lambda)
    
    x_now = y_next[0:3 , :]
    Lambda = y_next[3]
    
    y_list.append(y_next)
    steps = steps+1
    
print("last y: \n",y_list[-1])
print("iteration times: ", steps)

last y: 
 [[-0.03887348]
 [-0.36337461]
 [ 0.75729982]
 [ 1.02784794]]
iteration times:  1
last y: 
 [[ 0.10644144]
 [-0.24550746]
 [ 0.798067  ]
 [ 1.04691995]]
iteration times:  2
last y: 
 [[-0.00604273]
 [-0.31986936]
 [ 0.78492559]
 [ 1.06296344]]
iteration times:  3
last y: 
 [[ 0.07484838]
 [-0.25208836]
 [ 0.81165986]
 [ 1.07652221]]
iteration times:  4
last y: 
 [[ 0.00262753]
 [-0.29893451]
 [ 0.80446669]
 [ 1.08805928]]
iteration times:  5
last y: 
 [[ 0.05233247]
 [-0.25624311]
 [ 0.82196975]
 [ 1.09794112]]
iteration times:  6
last y: 
 [[ 0.00776986]
 [-0.28425656]
 [ 0.81824627]
 [ 1.10645517]]
iteration times:  7
last y: 
 [[ 0.03707666]
 [-0.25817559]
 [ 0.82923288]
 [ 1.11382823]]
iteration times:  8
last y: 
 [[ 0.01036105]
 [-0.27427572]
 [ 0.82741247]
 [ 1.12024181]]
iteration times:  9
last y: 
 [[ 0.02710645]
 [-0.25870842]
 [ 0.83410218]
 [ 1.12584386]]
iteration times:  10
last y: 
 [[ 0.00971182]
 [-0.26868942]
 [ 0.83317773]
 [ 1.13130312]]
iteration times:  

<ipython-input-9-b2a47f2ac671>:7: DeprecationWarning: setting an array element with a sequence. This was supported in some cases where the elements are arrays with a single element. For example `np.array([1, np.array([2])], dtype=int)`. In the future this will raise the same ValueError as `np.array([1, [2]], dtype=int)`.
  grad = np.array(grad,dtype = float)


last y: 
 [[ 0.01624493]
 [-0.25694272]
 [ 0.84154448]
 [ 1.15452516]]
iteration times:  18
last y: 
 [[ 0.01057493]
 [-0.26157715]
 [ 0.84040817]
 [ 1.15679804]]
iteration times:  19
last y: 
 [[ 0.01634687]
 [-0.25801954]
 [ 0.84156958]
 [ 1.15893728]]
iteration times:  20
last y: 
 [[ 0.01182374]
 [-0.26237857]
 [ 0.84041753]
 [ 1.16098132]]
iteration times:  21
last y: 
 [[ 0.01708196]
 [-0.25975272]
 [ 0.84123945]
 [ 1.16296417]]
iteration times:  22
last y: 
 [[ 0.01320295]
 [-0.26433901]
 [ 0.83997164]
 [ 1.16513309]]
iteration times:  23
last y: 
 [[ 0.01894163]
 [-0.26191047]
 [ 0.84069068]
 [ 1.16708279]]
iteration times:  24
last y: 
 [[ 0.0151952 ]
 [-0.26701127]
 [ 0.83923392]
 [ 1.16927566]]
iteration times:  25
last y: 
 [[ 0.02207313]
 [-0.26455911]
 [ 0.83992853]
 [ 1.17152814]]
iteration times:  26
last y: 
 [[ 0.01733686]
 [-0.27105831]
 [ 0.83803844]
 [ 1.17386972]]
iteration times:  27
last y: 
 [[ 0.02603605]
 [-0.26794208]
 [ 0.83889436]
 [ 1.17632838]]
iteration